### ISSUE TITLE
Relay access denied: How to solve

### ISSUE THREAD

**Issue by marcellodesales** [MarvAmBass/docker-versatile-postfix#1]
## Setting up keys
- Generated the keys as required

```
opendkim-genkey -s mail -d hub.docker.company.net
```
- I mounted the volume with the location of the keys... See the following Docker-Compose file with the entire setup.

``` yml
mailData:
  image: busybox
  volumes:
    - ./email-server-data/var-mail:/var/mail
    - ./email-server-data/dkim:/etc/postfix/dkim

coreOSRegistryServerEmail:
  image: marvambass/versatile-postfix
  command: hub.docker.company.net admin:word#pass0
  environment:
    ALIASES: "postmaster:root;hostmaster:root;webmaster:root"
  volumes_from:
    - "mailData"
  ports:
    - "587:25"
  labels:
    net.intuit.docker.ci.description: "Docker Registry Email Server"
```
## Relay access denied
- The client is running at `hub.docker.company.net`.
- The server is running at `ci.docker.company.net`.
- I'm trying to send emails from to `mdesales@corp.company.net` I'm getting the error `Relay access denied`.

This is the output of the logs when attempting to send emails from this server.

```
coreOSRegistryServerEmail_1 | Jan 20 16:37:14 6e4b4b7f935c postfix/smtpd[187]: connect from pprdespap321.corp.company.net[10.137.55.21]
coreOSRegistryServerEmail_1 | Jan 20 16:37:14 6e4b4b7f935c postfix/smtpd[187]: NOQUEUE: reject: RCPT from pprdespap321.corp.company.net[10.137.55.21]: 454 4.7.1 <mdesales@corp.company.net>: Relay access denied; from=<no-reply@hub.docker.company.net> to=<mdesales@corp.company.net> proto=ESMTP helo=<[192.168.4.1]>
coreOSRegistryServerEmail_1 | Jan 20 16:37:14 6e4b4b7f935c postfix/smtpd[187]: disconnect from pprdespap321.corp.company.net[10.137.55.21]
```
# Question
- How to enable relay?
- Does the file trusted-hosts work? http://www.stevejenkins.com/blog/2011/08/installing-opendkim-rpm-via-yum-with-postfix-or-sendmail-for-rhel-centos-fedora/
