### ISSUE TITLE
Is there a way to create health check in docker compose?

### ISSUE THREAD

**Issue by gromspys** [MarvAmBass/docker-versatile-postfix#17]
I use docker compose to run image and I can't find a way to create health check.
For example, when I use redis I can create healthcheck like:
```
version: '3.8'
services:
  redis:
    restart: always
    image: redis:6.2-alpine
....
  healthcheck:
    test: ["CMD", "redis-cli", "ping"]
    interval: 1s
    timeout: 3s
    retries: 10
....
```
Is there some command that can be used for healthcheck to restart container if something wrong inside?
